### ISSUE TITLE
Essentials Exception

### ISSUE THREAD

**Issue by TekuSP** [TekuSP/PrometheusServer#2]
[14:47:10] [Server thread/WARN] [com.earth2me.essentials.Essentials/]: [Essentials] Task #30 for Essentials vPre2.14.1.3 generated an exception
java.lang.NullPointerException
	at com.earth2me.essentials.xmpp.XMPPManager.updatePresence(XMPPManager.java:176) ~[?:?]
	at com.earth2me.essentials.xmpp.EssentialsXMPP.updatePresence(EssentialsXMPP.java:123) ~[?:?]
	at com.earth2me.essentials.xmpp.EssentialsXMPPPlayerListener$1.run(EssentialsXMPPPlayerListener.java:35) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:1.7.10-1566.UNOFFICIAL]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-1566.UNOFFICIAL]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:873) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]

**Comment by TekuSP** [comment]
Vypadá to na problém s XMPP. XMPP nepouživáme, takže ho vyřadíme.
